### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by grcasanova** [bahusvel/ExtraMalloc#1]
The library, when loaded dynamically, crashes the application with the following error:

> Could not seek: Bad file descriptor

Tested with most common software on Ubuntu 14.04 VM

**Comment by bahusvel** [comment]
Hi, if you would like to use this library for encryption please use: https://github.com/bahusvel/CryptoMalloc. That one will work and it perform significantly better than this repo. This repo is just an old fork. I'll be sure to note that on the front page so that others don't experience similar issues, the README.md is somewhat misleading :)
